## 1–1. Importing and defining a Sample Image:

In [3]:
import torch
import torch.nn as nn

# Sample 5x5 image
image = torch.tensor([[1, 2, 0, 1, 0],
                      [4, 1, 0, 0, 1],
                      [3, 0, 2, 4, 1],
                      [0, 1, 3, 0, 2],
                      [1, 0, 2, 1, 0]]).float().unsqueeze(0).unsqueeze(0)

print(image)

tensor([[[[1., 2., 0., 1., 0.],
          [4., 1., 0., 0., 1.],
          [3., 0., 2., 4., 1.],
          [0., 1., 3., 0., 2.],
          [1., 0., 2., 1., 0.]]]])


## 1-2. Defining and Applying the Convolutional Filter:

In [ ]:
# Define a 3x3 filter (kernel)
conv_filter = nn.Conv2d(in_channels=1, 
                        out_channels=1, 
                        kernel_size=3)

# Apply the filter to the image
output = conv_filter(image)
print(output)

tensor([[[[1.3104, 0.4814, 1.2380],
          [0.8508, 1.6306, 1.8392],
          [1.3923, 2.1132, 1.8383]]]], grad_fn=<ConvolutionBackward0>)


In [9]:
# Define a 3x3 filter (kernel) with padding=1
conv_filter = nn.Conv2d(in_channels=1, 
                        out_channels=1, 
                        kernel_size=3, 
                        padding=1)

# Apply the filter to the image
output = conv_filter(image)

print("Output shape:", output.shape)  
print()
print(output) 

Output shape: torch.Size([1, 1, 5, 5])

tensor([[[[ 7.4637e-04,  1.3144e+00,  7.6521e-01, -1.9651e-02,  4.4438e-01],
          [-5.0043e-01,  1.3312e+00, -5.3966e-01,  8.3514e-01,  1.4305e+00],
          [ 3.5473e-02,  4.0423e-01,  4.0923e-01,  1.2119e-01,  7.7568e-01],
          [ 7.3358e-01, -3.1308e-01, -9.0896e-01,  1.6058e+00,  8.9814e-01],
          [-5.5166e-02, -3.0160e-01,  5.7940e-01,  1.5919e-01,  7.0112e-01]]]],
       grad_fn=<ConvolutionBackward0>)


In [10]:
# Define a 3x3 filter (kernel) with padding and stride  
conv_filter = nn.Conv2d(in_channels=1,   
                        out_channels=1,   
                        kernel_size=3,   
                        padding=1,  # Adding padding of 1  
                        stride=1)   # Default stride of 1  

# Apply the filter to the image  
output = conv_filter(image)  

# Print the output  
print("Output shape:", output.shape)  
print()
print(output) 

Output shape: torch.Size([1, 1, 5, 5])

tensor([[[[ 0.0894, -0.5650,  0.0181, -0.4018, -0.2140],
          [-0.3753, -1.2723, -0.7991, -0.4310, -0.5797],
          [-1.4903, -0.7047,  0.5139, -0.5533, -0.5756],
          [-0.6997,  0.1195, -0.7214, -0.8971, -1.0950],
          [-0.1905,  0.3710, -0.9700, -0.4185, -0.7076]]]],
       grad_fn=<ConvolutionBackward0>)


In [14]:
# Define a 3x3 filter (kernel) with padding and stride  
conv_filter = nn.Conv2d(in_channels=1,   
                        out_channels=1,   
                        kernel_size=3,   
                        padding=1,  # Adding padding of 1  
                        stride=2)   # Default stride of 1  

# Apply the filter to the image  
output = conv_filter(image)  

# Print the output  
print("Output shape:", output.shape)  
print()
print(output) 

Output shape: torch.Size([1, 1, 3, 3])

tensor([[[[ 0.5277, -0.2819,  0.1669],
          [ 1.1605, -0.2568,  1.2595],
          [ 0.4100,  0.1643, -0.0399]]]], grad_fn=<ConvolutionBackward0>)


In [ ]:
# Function to perform convolution and print output shape  
def apply_convolution(image, padding, stride):  
    conv_filter = nn.Conv2d(in_channels=1,   
                            out_channels=1,   
                            kernel_size=3,   
                            padding=padding,   
                            stride=stride)  

    output = conv_filter(image)  
    print(f"Padding:{padding}, Stride:{stride} → Output shape:{output.shape}")  


print('Original image shape:', '\n', image.shape)

print("\nWithout Padding, Stride = 1")  
apply_convolution(image, padding=0, stride=1)  

print("\nWithout Padding, Stride = 2")  
apply_convolution(image, padding=0, stride=2)  

print("\nWith Padding, Stride = 1")  
apply_convolution(image, padding=1, stride=1)  

print("\nWith Padding, Stride = 2")  
apply_convolution(image, padding=1, stride=2)

Original image shape: 
 torch.Size([1, 1, 5, 5])

Without Padding, Stride = 1
Padding:0, Stride:1 → Output shape:torch.Size([1, 1, 3, 3])

Without Padding, Stride = 2
Padding:0, Stride:2 → Output shape:torch.Size([1, 1, 2, 2])

With Padding, Stride = 1
Padding:1, Stride:1 → Output shape:torch.Size([1, 1, 5, 5])

With Padding, Stride = 2
Padding:1, Stride:2 → Output shape:torch.Size([1, 1, 3, 3])


## Example 1: 32x32 Image, 5x5 Filter, Padding = 1, Stride = 2

In [ ]:
import torch  
import torch.nn as nn  

# Define the parameters  
image_size = 32   
filter_size = 5   
padding = 1     
stride = 2       

# Create a convolutional layer with the specified parameters  
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, 
                       kernel_size=filter_size, 
                       padding=padding, stride=stride)  

# Create a dummy input tensor with shape (Batch_size, Channels, Height, Width)  
dummy_input = torch.randn(1, 1, image_size, image_size)  

# Calculate the output by passing the dummy input through the convolutional layer  
output = conv_layer(dummy_input)  

# Output size  
output_size = output.shape[2]  # Height/Width of the output (they're the same in this case)  

print("Output Size for Example 1:", output_size)  # This should print 15

Output Size for Example 1: 15


## Example 2: 28x28 Image, 3x3 Filter, Padding = 0, Stride = 1

In [ ]:
import torch  
import torch.nn as nn  

# Define the parameters  
image_size = 28    
filter_size = 3  
padding = 0       
stride = 1       

# Create a convolutional layer with the specified parameters  
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, 
                       kernel_size=filter_size, 
                       padding=padding, stride=stride)  

# Create a dummy input tensor with shape (Batch_size, Channels, Height, Width)  
dummy_input = torch.randn(1, 1, image_size, image_size)  

# Passing the dummy input through the convolutional layer  
output = conv_layer(dummy_input)  

# Output size  
output_size = output.shape[2]  # Height/Width are the same in this case)  

print("Output Size for Example 2:", output_size) 

Output Size for Example 2: 26
