# 📝 **NumPy Assignment Series**

## Assignment 1: Array Creation and Initialization

### **Concept:**
Learn how to create and initialize NumPy arrays using different methods.

### **Tasks:**

1. **Create an array from a list:**  
   Convert the following list into a NumPy array: `[1, 2, 3, 4, 5]`.

2. **Create arrays using functions:**  
   - Create an array of zeros with shape `(3, 3)`.
   - Create an array of ones with shape `(2, 4)`.
   - Create an array of evenly spaced values between 0 and 10 with a step of 2.

3. **Create an identity matrix:**  
   Create a 4x4 identity matrix.

### **Solution:**

In [1]:
import numpy as np

# 1. Create an array from a list
arr1 = np.array([1, 2, 3, 4, 5])

# 2. Create arrays using functions
arr_zeros = np.zeros((3, 3))
arr_ones = np.ones((2, 4))
arr_linspace = np.arange(0, 11, 2)

# 3. Create an identity matrix
identity_matrix = np.eye(4)

print(arr1)
print(arr_zeros)
print(arr_ones)
print(arr_linspace)
print(identity_matrix)

[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 0  2  4  6  8 10]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Assignment 2: Array Manipulation

### **Concept:**
Learn how to reshape, flatten, and concatenate arrays.

### **Tasks:**

1. **Reshape an array:**  
   Reshape the array `[1, 2, 3, 4, 5, 6]` into a 2x3 matrix.

2. **Flatten a 2D array:**  
   Flatten the following 2D array:  
   ```
   [[1, 2, 3],
    [4, 5, 6]]
   ```

3. **Concatenate arrays:**  
   Concatenate the arrays `[1, 2, 3]` and `[4, 5, 6]` horizontally.

### **Solution:**

In [2]:
# 1. Reshape an array
arr_reshape = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)

# 2. Flatten a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_flatten = arr_2d.flatten()

# 3. Concatenate arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_concat = np.concatenate((arr1, arr2))

print(arr_reshape)
print(arr_flatten)
print(arr_concat)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


## Assignment 3: Array Broadcasting

### **Concept:**
Practice broadcasting rules in NumPy for element-wise operations.

### **Tasks:**

1. **Add a scalar to an array:**  
   Add `10` to each element of the array `[1, 2, 3, 4]`.

2. **Add a 1D array to a 2D array:**  
   Add `[1, 2, 3]` to each row of the 2D array:  
   ```
   [[10, 20, 30],
    [40, 50, 60]]
   ```

### **Solution:**

In [ ]:
# 1. Add a scalar to an array
arr = np.array([1, 2, 3, 4])
arr_scalar = arr + 10

# 2. Add a 1D array to a 2D array
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
arr_1d = np.array([1, 2, 3])
arr_broadcast = arr_2d + arr_1d

print(arr_scalar)
print(arr_broadcast)

## Assignment 4: Mathematical Operations

### **Concept:**
Perform mathematical operations on NumPy arrays.

### **Tasks:**

1. **Element-wise operations:**  
   Given `arr1 = [1, 2, 3]` and `arr2 = [4, 5, 6]`, compute the following:
   - Sum of `arr1` and `arr2`
   - Product of `arr1` and `arr2`

2. **Compute mean and standard deviation:**  
   Calculate the mean and standard deviation of the array `[2, 4, 6, 8, 10]`.

### **Solution:**

In [ ]:
# 1. Element-wise operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr_sum = arr1 + arr2
arr_product = arr1 * arr2

# 2. Compute mean and standard deviation
arr = np.array([2, 4, 6, 8, 10])
mean = np.mean(arr)
std_dev = np.std(arr)

print(arr_sum)
print(arr_product)
print(f"Mean: {mean}, Standard Deviation: {std_dev}")

## Assignment 5: Indexing and Slicing

### **Concept:**
Practice advanced indexing and slicing techniques in NumPy.

### **Tasks:**

1. **Indexing:**  
   Extract the element at position `(1, 2)` from the following array:  
   ```
   [[10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]]
   ```

2. **Slicing:**  
   Extract the second row and first two columns from the array above.

3. **Boolean indexing:**  
   Given `arr = [5, 10, 15, 20]`, extract elements greater than `10`.

### **Solution:**

In [ ]:
# Given array
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# 1. Indexing
element = arr_2d[1, 2]

# 2. Slicing
slice_part = arr_2d[1, :2]

# 3. Boolean indexing
arr = np.array([5, 10, 15, 20])
filtered = arr[arr > 10]

print(element)
print(slice_part)
print(filtered)

## Assignment 6: Common Functions

### **Concept:**
Explore common NumPy functions such as `sum`, `max`, `min`, and `argmax`.

### **Tasks:**

1. **Compute sum and max:**  
   Given the array `[3, 7, 2, 9, 5]`, compute the sum and maximum value.

2. **Find the index of the maximum value:**  
   Find the index of the maximum value in the same array.

### **Solution:**

In [ ]:
arr = np.array([3, 7, 2, 9, 5])

# Sum and max
total = np.sum(arr)
maximum = np.max(arr)

# Index of max
index_max = np.argmax(arr)

print(f"Sum: {total}, Max: {maximum}, Index of Max: {index_max}")

## Assignment 7: Array Creation with Random Numbers

### **Concept:**
Creating arrays using random number generation.

### **Tasks:**

1. **Generate a random 3x3 array of floats between 0 and 1.**

2. **Create a 4x4 array of random integers between 10 and 50.**

3. **Set a random seed to make the random numbers reproducible. Generate a 2x3 array of random numbers.**

### **Solution:**

In [ ]:
import numpy as np

# 1. Random 3x3 array of floats
random_floats = np.random.rand(3, 3)

# 2. Random 4x4 array of integers between 10 and 50
random_integers = np.random.randint(10, 50, size=(4, 4))

# 3. Reproducible random numbers with a seed
np.random.seed(42)
random_seeded = np.random.rand(2, 3)

print(random_floats)
print(random_integers)
print(random_seeded)

## Assignment 8: Advanced Array Manipulation

### **Concept:**
Stacking and splitting arrays.

### **Tasks:**

1. **Vertically stack the following arrays:**  
   ```
   arr1 = [[1, 2], [3, 4]]
   arr2 = [[5, 6], [7, 8]]
   ```

2. **Horizontally stack the same arrays.**

3. **Split the following array into 3 equal parts along the first axis:**  
   ```
   arr = [[1, 2], [3, 4], [5, 6]]
   ```

### **Solution:**

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# 1. Vertical stacking
vstack_result = np.vstack((arr1, arr2))

# 2. Horizontal stacking
hstack_result = np.hstack((arr1, arr2))

# 3. Splitting an array
arr = np.array([[1, 2], [3, 4], [5, 6]])
split_result = np.array_split(arr, 3)

print(vstack_result)
print(hstack_result)
print(split_result)

## Assignment 9: Broadcasting and Advanced Arithmetic

### **Concept:**
Performing broadcasting with arithmetic operations.

### **Tasks:**

1. **Broadcast the following 1D array to a 3x3 array and add:**  
   ```
   base = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
   add_array = [10, 20, 30]
   ```

2. **Multiply a 3x3 matrix by a scalar value of 2.**

3. **Divide each row of the following matrix by a different value:**  
   ```
   arr = [[10, 20, 30],
          [40, 50, 60],
          [70, 80, 90]]
   divisors = [10, 20, 30]
   ```

### **Solution:**

In [ ]:
# 1. Broadcasting addition
base = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
add_array = np.array([10, 20, 30])
result_add = base + add_array

# 2. Scalar multiplication
result_mult = base * 2

# 3. Row-wise division
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
divisors = np.array([10, 20, 30]).reshape(3, 1)
result_div = arr / divisors

print(result_add)
print(result_mult)
print(result_div)

## Assignment 10: Indexing, Slicing, and Fancy Indexing

### **Concept:**
Practice with indexing techniques and fancy indexing.

### **Tasks:**

1. **Extract all even numbers from the following array:**  
   ```
   arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
   ```

2. **Using fancy indexing, select the elements at positions `[0, 2, 4]` from the array:**  
   ```
   arr = [10, 20, 30, 40, 50]
   ```

3. **Extract the second and third rows and the first and second columns from this 2D array:**  
   ```
   arr = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [10, 11, 12]]
   ```

### **Solution:**

In [ ]:
# 1. Extract even numbers
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = arr[arr % 2 == 0]

# 2. Fancy indexing
arr2 = np.array([10, 20, 30, 40, 50])
fancy_selected = arr2[[0, 2, 4]]

# 3. Extract specific rows and columns
arr3 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])
sliced_part = arr3[1:3, 0:2]

print(even_numbers)
print(fancy_selected)
print(sliced_part)

## Assignment 11: Common Functions and Statistics

### **Concept:**
Using NumPy's built-in statistical functions.

### **Tasks:**

1. **Find the minimum, maximum, and sum of the following array:**  
   ```
   arr = [3, 7, 1, 9, 5]
   ```

2. **Compute the mean, median, and standard deviation of the following array:**  
   ```
   arr = [10, 20, 30, 40, 50]
   ```

3. **Find the indices of the minimum and maximum values in the array:**  
   ```
   arr = [4, 2, 9, 1, 6]
   ```

### **Solution:**

In [ ]:
# 1. Min, max, and sum
arr1 = np.array([3, 7, 1, 9, 5])
min_val = np.min(arr1)
max_val = np.max(arr1)
total_sum = np.sum(arr1)

# 2. Mean, median, and std
arr2 = np.array([10, 20, 30, 40, 50])
mean_val = np.mean(arr2)
median_val = np.median(arr2)
std_val = np.std(arr2)

# 3. Indices of min and max
arr3 = np.array([4, 2, 9, 1, 6])
index_min = np.argmin(arr3)
index_max = np.argmax(arr3)

print(f"Min: {min_val}, Max: {max_val}, Sum: {total_sum}")
print(f"Mean: {mean_val}, Median: {median_val}, Std Dev: {std_val}")
print(f"Index of Min: {index_min}, Index of Max: {index_max}")