# 📝 **NumPy Assignment Series**

## Assignment 1: Array Creation and Initialization

### **Concept:**
Learn how to create and initialize NumPy arrays using different methods.

### **Tasks:**

1. **Create an array from a list:**  
   Convert the following list into a NumPy array: `[1, 2, 3, 4, 5]`.

2. **Create arrays using functions:**  
   - Create an array of zeros with shape `(3, 3)`.
   - Create an array of ones with shape `(2, 4)`.
   - Create an array of evenly spaced values between 0 and 10 with a step of 2.

3. **Create an identity matrix:**  
   Create a 4x4 identity matrix.

### **Solution:**

## Assignment 2: Array Manipulation

### **Concept:**
Learn how to reshape, flatten, and concatenate arrays.

### **Tasks:**

1. **Reshape an array:**  
   Reshape the array `[1, 2, 3, 4, 5, 6]` into a 2x3 matrix.

2. **Flatten a 2D array:**  
   Flatten the following 2D array:  
   ```
   [[1, 2, 3],
    [4, 5, 6]]
   ```

3. **Concatenate arrays:**  
   Concatenate the arrays `[1, 2, 3]` and `[4, 5, 6]` horizontally.

### **Solution:**

## Assignment 3: Array Broadcasting

### **Concept:**
Practice broadcasting rules in NumPy for element-wise operations.

### **Tasks:**

1. **Add a scalar to an array:**  
   Add `10` to each element of the array `[1, 2, 3, 4]`.

2. **Add a 1D array to a 2D array:**  
   Add `[1, 2, 3]` to each row of the 2D array:  
   ```
   [[10, 20, 30],
    [40, 50, 60]]
   ```

### **Solution:**

In [1]:
import numpy as np  

# Create a 3D matrix (shape: 2x3x4)  
matrix_3d = np.array([[[1, 2, 3, 4],   
                        [5, 6, 7, 8],   
                        [9, 10, 11, 12]],   
                       
                       [[13, 14, 15, 16],   
                        [17, 18, 19, 20],   
                        [21, 22, 23, 24]]])  

# Create a 1D vector (shape: 4)  
vector_1d = np.array([10, 20, 30, 40])  

# Add the 1D vector to the 3D matrix using broadcasting  
result = matrix_3d + vector_1d  

print("3D Matrix:")  
print(matrix_3d)  
print("\n1D Vector:")  
print(vector_1d)  
print("\nResult after broadcasting addition:")  
print(result)

3D Matrix:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

1D Vector:
[10 20 30 40]

Result after broadcasting addition:
[[[11 22 33 44]
  [15 26 37 48]
  [19 30 41 52]]

 [[23 34 45 56]
  [27 38 49 60]
  [31 42 53 64]]]


## Assignment 4: Mathematical Operations

### **Concept:**
Perform mathematical operations on NumPy arrays.

### **Tasks:**

1. **Element-wise operations:**  
   Given `arr1 = [1, 2, 3]` and `arr2 = [4, 5, 6]`, compute the following:
   - Sum of `arr1` and `arr2`
   - Product of `arr1` and `arr2`

2. **Compute mean and standard deviation:**  
   Calculate the mean and standard deviation of the array `[2, 4, 6, 8, 10]`.

### **Solution:**

## Assignment 5: Indexing and Slicing

### **Concept:**
Practice advanced indexing and slicing techniques in NumPy.

### **Tasks:**

1. **Indexing:**  
   Extract the element at position `(1, 2)` from the following array:  
   ```
   [[10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]]
   ```

2. **Slicing:**  
   Extract the second row and first two columns from the array above.

3. **Boolean indexing:**  
   Given `arr = [5, 10, 15, 20]`, extract elements greater than `10`.

### **Solution:**

## Assignment 6: Common Functions

### **Concept:**
Explore common NumPy functions such as `sum`, `max`, `min`, and `argmax`.

### **Tasks:**

1. **Compute sum and max:**  
   Given the array `[3, 7, 2, 9, 5]`, compute the sum and maximum value.

2. **Find the index of the maximum value:**  
   Find the index of the maximum value in the same array.

### **Solution:**

## Assignment 7: Array Creation with Random Numbers

### **Concept:**
Creating arrays using random number generation.

### **Tasks:**

1. **Generate a random 3x3 array of floats between 0 and 1.**

2. **Create a 4x4 array of random integers between 10 and 50.**

3. **Set a random seed to make the random numbers reproducible. Generate a 2x3 array of random numbers.**

### **Solution:**

## Assignment 8: Advanced Array Manipulation

### **Concept:**
Stacking and splitting arrays.

### **Tasks:**

1. **Vertically stack the following arrays:**  
   ```
   arr1 = [[1, 2], [3, 4]]
   arr2 = [[5, 6], [7, 8]]
   ```

2. **Horizontally stack the same arrays.**

3. **Split the following array into 3 equal parts along the first axis:**  
   ```
   arr = [[1, 2], [3, 4], [5, 6]]
   ```

### **Solution:**

## Assignment 9: Broadcasting and Advanced Arithmetic

### **Concept:**
Performing broadcasting with arithmetic operations.

### **Tasks:**

1. **Broadcast the following 1D array to a 3x3 array and add:**  
   ```
   base = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
   add_array = [10, 20, 30]
   ```

2. **Multiply a 3x3 matrix by a scalar value of 2.**

3. **Divide each row of the following matrix by a different value:**  
   ```
   arr = [[10, 20, 30],
          [40, 50, 60],
          [70, 80, 90]]
   divisors = [10, 20, 30]
   ```

### **Solution:**

## Assignment 10: Indexing, Slicing, and Fancy Indexing

### **Concept:**
Practice with indexing techniques and fancy indexing.

### **Tasks:**

1. **Extract all even numbers from the following array:**  
   ```
   arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
   ```

2. **Using fancy indexing, select the elements at positions `[0, 2, 4]` from the array:**  
   ```
   arr = [10, 20, 30, 40, 50]
   ```

3. **Extract the second and third rows and the first and second columns from this 2D array:**  
   ```
   arr = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [10, 11, 12]]
   ```

### **Solution:**

## Assignment 11: Common Functions and Statistics

### **Concept:**
Using NumPy's built-in statistical functions.

### **Tasks:**

1. **Find the minimum, maximum, and sum of the following array:**  
   ```
   arr = [3, 7, 1, 9, 5]
   ```

2. **Compute the mean, median, and standard deviation of the following array:**  
   ```
   arr = [10, 20, 30, 40, 50]
   ```

3. **Find the indices of the minimum and maximum values in the array:**  
   ```
   arr = [4, 2, 9, 1, 6]
   ```

### **Solution:**